### ISSUE TITLE
Invalid configuration error

### ISSUE THREAD

**Issue by jklegseth** [piecioshka/boilerplate-babel-webpack#1]
Tried the repo today and at `npm run build` got:

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "./public/dist" is not an absolute path!
```

MacBook Pro Sierra 10.12.3

Looks like this can be solved using `__dirname` instead of `./` on line 10 of `webpack.config.js`:

```
path: __dirname + '/public/dist'
```

**Comment by piecioshka** [comment]
@jklegseth thanks for your issue.

v1.0.2 resolve this error.
